### ISSUE TITLE
Discourage dark patterns

### ISSUE THREAD

**Issue by kdekooter** [inthepocket/cookie-though#2]
The default button in a cookie nagger should preferably be "Enable the strictly necessary" and not "Accept all". 

The sample dialog has a darkish-pattern IMO. A user has to notice that "Customize" is a link. It needs to clicked first to see what the customizable options are. That makes for two extra clicks.

**Comment by LukasCornille** [comment]
Hi, as you can read in the docs, [the permission labels](https://cookiethough.dev/configuration/#permissionlabels), are fully customisable, we've decided on using these labels. The same can be said about [the customize label](https://cookiethough.dev/configuration/#customizelabel). 

If a developer wants to adjust this to make it more visible, they are free to do so by adjusting the labels.
For your request, you could just adjust the decline label to: "Enable the strictly necessary".

**Comment by louisdj** [comment]
I always find this an interesting discussion, but the decline button is already giving only the strictly necessary cookies; instead of forcing the user trough the customisation options to not accepting all cookies like we see on a lot of website...

**Comment by kdekooter** [comment]
Uhm so "decline" is actually not declining all cookies? Sounds dark to me ;-).

**Comment by LukasCornille** [comment]
@kdekooter following the GDPR guidelines, it isn't required to get consent from the user for strictly necessary cookies as they are required for a user to be able to user the site. So there's nothing dark about it ;)

**Comment by louisdj** [comment]
Indeed, the strictly necessary cookies will be already placed before the cookie consent is asked, I agree it can be somehow confusing from the copy, but this can be changed if you want. 
It is the responsibility of the developer implementing to be very selective on which cookies are strictly necessary, and to follow the guidelines of the local authority (the Belgian advice of the GBA can be found [here](https://www.gegevensbeschermingsautoriteit.be/burger/thema-s/internet/cookies)) .

**Comment by kdekooter** [comment]
Great! So if your site only depends on these kinds of cookies you don't need a consent form at all 🎉! 

With a self-hosted analytics solution and the notion that personalized ads are being abandoned shortly (see https://www.beyond-print.net/market-google-stops-personalized-advertising/) you can give your users a hassle-free experience and still monitor your site properly.

Too bad there is no use for this otherwise very nice UI library anymore then ...
