### ISSUE TITLE
Add extra CSS variables

### ISSUE THREAD

**Issue by benoitblancquaert** [inthepocket/cookie-though#216]
Is it possible to add some more CSS variables such as:
- Button (`.ct-button`) padding
- Button border
- Button border-radius
- Container (`.cookie-though`) border-radius

Please 🐱

**Comment by LukasCornille** [comment]
Hey Benoit,

As for the .cookie-though container, you're able to style it by targeting the `.cookie-though` class as it's not inside the shadow DOM.

For the button variables, seeing that the library fits our, and most other implementation, needs we don't want to add more variables just for a single implementation. So for now, we won't be adding these.

That's not to say that you can't style them though :wink:. You can write a JS/TS function, which either:

- creates a style tag which can then be appended inside the shadow DOM.
- selects the buttons, and then add styling with JS

The following code snippet is an example of adding styling with JS:

```js
const overwriteCSS = () => {
  const cookieThough = document.querySelector('.cookie-though');
  const [declineButton, acceptButton] = cookieThough.shadowRoot.querySelectorAll('.ct-button');


  declineButton.style.border = '1px solid red';
};
```

**Comment by benoitblancquaert** [comment]
Perfect! That works!

But now I'm looking how to run that snippet in a callback after the initialization. I'm using CookieThough via CDN in an older ES5 project.

**Comment by LukasCornille** [comment]
Hey Benoit, normally when you call the init() function, you should be able to access the banner, so just calling a new function should work!

Let me know if this solves it for you 😄

**Comment by robrechtme** [comment]
I'm sorry but some extra button styles would really come in useful. I also had several occasions where I wanted to change the button's border radius and padding. The solutions you provide work but it's not easy and scatters your cookie-though styles over many places. 

I think some extra CSS variables won't hurt? 😄

**Comment by LukasCornille** [comment]
Hey Robrecht,

I've built a v2 recently, which also requires the docs to be updated. I'll make sure to add the button radius and padding to this version!

Just need to have the time to further create the new docs 😅
