### ISSUE TITLE
No touch events on mobile

### ISSUE THREAD

**Issue by gertst** [inthepocket/cookie-though#6]
No buttons seam to work on mobile. Both on Android Chrome or iPad Safari.

I've added remote debugging and I got this error when I click a button (or the arrow):

fastclick.js:9 [Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080
FastClick.onTouchStart @ fastclick.js:9
(anonymous) @ fastclick.js:9

The click event on the button is never triggered.

I'm using the latest version 1.1.3 from https://unpkg.com/cookie-though@1.1.3

All is working well on desktop.

Any thoughts?

Tnx!

**Comment by LukasCornille** [comment]
Hi, thanks for listing an issue to our repo!

I've tested this on a website in production on v1.1.3 on an ipad using Safari and I can't seem to reproduce this, as you can see from the video below all the events on any of the clickable elements get triggered accordingly. Would it be possible to show us a demo of the event listeners not being triggered through a video or code?


https://user-images.githubusercontent.com/36887321/111760238-c36f6580-889e-11eb-9f0e-cb0b76e07692.mp4

**Comment by gertst** [comment]
Thanks for the swift response!

I'm trying to integrate CookieThough on this site (dev): https://corp-site.dynapac.dev.buthost.com/en

As you can see it's not working on mobile. The site is old and made on old technology, but I guess that's not causing the issue ;)

Here's a screenshot of the remote debugging panel in Chrome on Android. But it also has this on Safari with iPad.

![image](https://user-images.githubusercontent.com/4465007/111765502-b6557500-88a4-11eb-937f-73e266619c3b.png)

**Comment by gertst** [comment]
Hm, when I remove fastclick.js, the issue is gone!

Checking out why as we speak ...

**Comment by LukasCornille** [comment]
I visited the repository of fastclick, it seems as though this issue is an issue related to the library and shadow dom. As we're using shadow dom to encapsulate the css, this is most likely the root of your issue. 

This means however it's related to fastclick.js and not an issue we have to solve 😅
